function buildUI_v1(obj)
L0 = uiextras.HBox('Parent',obj.hfigUser,'Padding',5,'Spacing',10);

L0_1 = uiextras.VBox('Parent',L0,'Spacing',10);
L0_2 = uiextras.VBox('Parent',L0,'Spacing',10);

%% leftLayout, APT Configuration Interface
L0_1_1 = uiextras.HBox('Parent',L0_1);
L0_1_1_1 = uipanel('Parent',L0_1_1,...
    'Title','APT Configuration',...
    'FontSize',10,'fontweight','bold');
L0_1_1_1_1 = uiextras.VBox('Parent',L0_1_1_1);
% stage interface
L0_1_1_1_1_1 = uipanel('Parent',L0_1_1_1_1,...
    'Title','Stages',...
    'FontSize',9,'fontweight','bold');
L0_1_1_1_1_1_1 = uiextras.Grid('Parent',L0_1_1_1_1_1);
uicontrol('Parent',L0_1_1_1_1_1_1,...
    'style','text','string','X Start from, mm',...
    'horizontalalignment','right','fontweight','bold');
uicontrol('Parent',L0_1_1_1_1_1_1,...
    'style','text','string','Y Start from, mm',...
    'horizontalalignment','right','fontweight','bold');
uicontrol('Parent',L0_1_1_1_1_1_1,...
    'style','text','string','Z Start from, mm',...
    'horizontalalignment','right','fontweight','bold');
uicontrol('Parent',L0_1_1_1_1_1_1,...
    'style','text','string','Positioning Mode',...
    'horizontalalignment','right','fontweight','bold');

obj.stageVObj.stageXStartEdit = uicontrol('parent',L0_1_1_1_1_1_1,...
    'style','edit','string','15',...
    'horizontalalignment','left');
obj.stageVObj.stageYStartEdit = uicontrol('parent',L0_1_1_1_1_1_1,...
    'style','edit','string','15',...
    'horizontalalignment','left');
obj.stageVObj.stageZStartEdit = uicontrol('parent',L0_1_1_1_1_1_1,...
    'style','edit','string','21',...
    'horizontalalignment','left');
obj.stageVObj.positioningModePopup = uicontrol('parent',L0_1_1_1_1_1_1,...
    'style','popupmenu','string','Microstep3|Microstep2|Microstep|Encoder',...
    'horizontalalignment','left');

uicontrol('parent',L0_1_1_1_1_1_1,...
    'style','text','string','X Serial Num',...
    'horizontalalignment','right','fontweight','bold');
uicontrol('parent',L0_1_1_1_1_1_1,...
    'style','text','string','Y Serial Num',...
    'horizontalalignment','right','fontweight','bold');
uicontrol('parent',L0_1_1_1_1_1_1,...
    'style','text','string','Z Serial Num',...
    'horizontalalignment','right','fontweight','bold');
%uiextras.Empty('parent',L0_1_1_1_1_1_1);% dont know why here will not empty
uicontrol('parent',L0_1_1_1_1_1_1,...
    'style','text','string','',...
    'horizontalalignment','right','fontweight','bold');


obj.stageVObj.snXEdit = uicontrol('parent',L0_1_1_1_1_1_1,...
    'style','edit','string','90871281',...
    'horizontalalignment','left');
obj.stageVObj.snYEdit = uicontrol('parent',L0_1_1_1_1_1_1,...
    'style','edit','string','90871282',...
    'horizontalalignment','left');
obj.stageVObj.snZEdit = uicontrol('parent',L0_1_1_1_1_1_1,...
    'style','edit','string','90871283',...
    'horizontalalignment','left');
uiextras.Empty('Parent',L0_1_1_1_1_1_1);
set(L0_1_1_1_1_1_1,'rowsizes',[-1,-1,-1,-1],...
    'columnsizes',[-0.3,-0.3,-0.3,-0.3],...
    'spacing',5,'padding',5);

% piezo interface
L0_1_1_1_1_2 = uipanel('Parent',L0_1_1_1_1,...
    'Title','Piezo','FontSize',9,'fontweight','bold');
L0_1_1_1_1_2_1 = uiextras.Grid('Parent',L0_1_1_1_1_2);
uicontrol('Parent',L0_1_1_1_1_2_1,...
    'style','text','string','Start from, um',...
    'horizontalalignment','right','fontweight','bold');
uiextras.Empty('Parent',L0_1_1_1_1_2_1);

obj.piezoVObj.piezoStartEdit = uicontrol('parent',L0_1_1_1_1_2_1,...
    'style','edit','string','0',...
    'horizontalalignment','left');
uiextras.Empty('Parent',L0_1_1_1_1_2_1);

uicontrol('Parent',L0_1_1_1_1_2_1,...
    'style','text','string','Serial Num',...
    'horizontalalignment','right','fontweight','bold');
uiextras.Empty('Parent',L0_1_1_1_1_2_1);

obj.piezoVObj.snEdit = uicontrol('parent',L0_1_1_1_1_2_1,...
    'style','edit','string','44000121',...
    'horizontalalignment','left');
uiextras.Empty('Parent',L0_1_1_1_1_2_1);

set(L0_1_1_1_1_2_1,'rowsizes',[-1,-1,-1,-1],...
    'columnsizes',[-0.3,-0.3,-0.3,-0.3],...
    'spacing',5,'padding',5);

% option interface
L0_1_1_1_1_3 = uiextras.HBox('Parent',L0_1_1_1_1);
uiextras.Empty('Parent',L0_1_1_1_1_3);
uiextras.Empty('Parent',L0_1_1_1_1_3);
obj.stageVObj.initiateButton = uicontrol('parent',L0_1_1_1_1_3,...
    'style','pushbutton','string','Initiate stages','fontweight','bold');
obj.piezoVObj.initiateButton= uicontrol('parent',L0_1_1_1_1_3,...
    'style','pushbutton','string','Initiate piezo','fontweight','bold');
set(L0_1_1_1_1_3,'sizes',[-1,-1,-1,-1],'spacing',10,'padding',2);

% setting of APT Configuration Interface
set(L0_1_1_1_1,'sizes',[-4.5,-2.75,-1],'spacing',5,'padding',5);
%% leftLayout, State Interface
L0_1_2 = uiextras.HBox('Parent',L0_1);
L0_1_2_1 = uipanel('Parent',L0_1_2,...
    'Title','State','FontSize',10,'fontweight','bold');
obj.userVObj.axDisplay = axes('Parent',L0_1_2_1,'Position',[0.1,0.1,0.85,0.85]);
obj.userVObj.axDisplay.NextPlot = 'add';
%% leftLayout, Log Interface
L0_1_3 = uiextras.HBox('Parent',L0_1);
L0_1_3_1 = uipanel('Parent',L0_1_3,'Title','Log',...
    'FontSize',10,'fontweight','bold');
%{
obj.userVObj.hLog = uicontrol('Parent',hPanel2,'style','edit','tag','log',...
    'max',2,'horizontalalignment','left','enable','inactive',...
    'FontSize',10,'Units','normalized','Position',[0.04,0.04,0.92,0.92]);
%}
L0_1_3_1_1 = uiextras.VBox('Parent',L0_1_3_1);
obj.userVObj.hLog = uicontrol('Parent',L0_1_3_1_1,...
    'style','edit','tag','log','max',2,...
    'horizontalalignment','left','enable','inactive','FontSize',10);
L0_1_3_1_1_1 = uiextras.HBox('Parent',L0_1_3_1_1);
uiextras.Empty('Parent',L0_1_3_1_1_1);
obj.userVObj.saveLogButton = uicontrol('Parent',L0_1_3_1_1_1,...
    'style','pushbutton','string','Save Log','fontweight','bold');
set(L0_1_3_1_1_1,'sizes',[-0.75,-0.25],'spacing',10);
set(L0_1_3_1_1,'sizes',[-0.86,-0.14],'spacing',5,'padding',10);
%% leftLayout, setting
set(L0_1,'sizes',[-0.28,-0.45,-0.22],'spacing',10,'padding',5);
%% rightLayout, camera
L0_2_1 = uiextras.VBox('Parent',L0_2);
L0_2_1_1 = uipanel('Parent',L0_2_1,...
    'Title','Camera','FontSize',10,'fontweight','bold');
L0_2_1_1_1 = uiextras.VBox('Parent',L0_2_1_1);
obj.cameraVObj.axCamera = axes('Parent',L0_2_1_1_1,...
    'XTickLabel','','YTickLabel','','box','on','Visible','off');

L0_2_1_1_1_1 =  uiextras.HBox('Parent',L0_2_1_1_1);
uiextras.Empty('Parent',L0_2_1_1_1_1);
obj.cameraVObj.cameraConnectText = uicontrol('parent',L0_2_1_1_1_1,...
    'style','togglebutton','string','Camera Disconnected',...
    'fontweight','bold','BackgroundColor',[0.64,0.08,0.18],...
    'ForegroundColor','w','enable','inactive');
obj.cameraVObj.cameraConnectButton = uicontrol('parent',L0_2_1_1_1_1,...
    'style','pushbutton','string','Connect Camera',...
    'fontweight','bold');
obj.cameraVObj.cameraDisconnectButton = uicontrol('parent',L0_2_1_1_1_1,...
    'style','pushbutton','string','Disonnect Camera',...
    'fontweight','bold');
uiextras.Empty('Parent',L0_2_1_1_1_1);
set(L0_2_1_1_1_1,'sizes',[-0.2,-0.2,-0.2,-0.2,-0.2],'spacing',10,'padding',5);

L0_2_1_1_1_2 = uiextras.HBox('Parent',L0_2_1_1_1);
L0_2_1_1_1_2_1 = uipanel('Parent',L0_2_1_1_1_2,...
    'Title','Configuration','FontSize',9,'fontweight','bold');
L0_2_1_1_1_2_1_1 = uiextras.HBox('Parent',L0_2_1_1_1_2_1);
obj.cameraVObj.setButton = uicontrol('parent',L0_2_1_1_1_2_1_1,...
    'style','pushbutton','string','Set','fontweight','bold');
obj.cameraVObj.loadButton = uicontrol('parent',L0_2_1_1_1_2_1_1,...
    'style','pushbutton','string','Load','fontweight','bold');
obj.cameraVObj.saveButton = uicontrol('parent',L0_2_1_1_1_2_1_1,...
    'style','pushbutton','string','Save','fontweight','bold');
set(L0_2_1_1_1_2_1_1,'spacing',10,'padding',5);
L0_2_1_1_1_2_2 = uipanel('Parent',L0_2_1_1_1_2,...
    'Title','Operation','FontSize',9,'fontweight','bold');
L0_2_1_1_1_2_2_1 = uiextras.HBox('Parent',L0_2_1_1_1_2_2);
obj.cameraVObj.startPreButton = uicontrol('parent',L0_2_1_1_1_2_2_1,...
    'style','pushbutton','string','Start preview',...
    'fontweight','bold','enable','on');
obj.cameraVObj.stopPreButton = uicontrol('parent',L0_2_1_1_1_2_2_1,...
    'style','pushbutton','string','Stop preview',...
    'fontweight','bold','enable','on');
obj.cameraVObj.captureTpiButton = uicontrol('parent',L0_2_1_1_1_2_2_1,...
    'style','pushbutton','string','Capture tpi',...
    'fontweight','bold','enable','off');
obj.cameraVObj.captureButton = uicontrol('parent',L0_2_1_1_1_2_2_1,...
    'style','pushbutton','string','Capture',...
    'fontweight','bold','enable','off');
set(L0_2_1_1_1_2_2_1,'spacing',10,'padding',5);
set(L0_2_1_1_1_2,'sizes',[-3,-4],'spacing',10,'padding',5);
set(L0_2_1_1_1,'sizes',[-0.84,-0.06,-0.1]);
uiextras.Empty('Parent',L0_2_1);
%% rUpperLayout, setting
set(L0_2_1,'sizes',[-2,-1],'spacing',10,'padding',5);
%% mainLayout, setting
set(L0,'sizes',[-1,-2],'spacing',10);
%% change camera axes size
pause(0.5);
set(obj.cameraVObj.axCamera,'Units','Normalized',...
    'Position',[0.198,0.12,0.5978,0.8587],'Visible','on'); % 0.6962 times
end